### PR TITLE
Use proper context on UIView.find

### LINKED ISSUE #74: Test for content in a custom table cell view
I am using a custom cell class in a table cell and passing it state. 

Here is my table cell view:
```ruby
class CustomCell < PM::TableViewCell
  def state=(state)
    build_initial_view unless view_built? # Lay out view unless already laid out
    find(contentView).tap do |c|
      c.find(:label).data(state[:key]) if state[:key] # Pass state to views
    end
  end

  def view_built?
    @view_built
  end

  def build_initial_view
    find(contentView).tap do |c|
      c.append(UILabel, :label)
    end
    @view_built = true
  end
end
```

In my spec I can then set my view's state by doing something like this:
```ruby
describe CustomCell do
  def cell
    @cell ||= CustomCell.new
  end

  def default_state
    {  key: "value"  }
  end

  before do
    cell.state = default_state # Setting state
  end

  after do
    @cell = nil
  end
end
```

What I am trying to do is then test for content like this:
```ruby
it "has content" do
  cell.find(:label).data.should == "value"
end
```

When I run my spec I get this error:
```bash
  CustomCell has content: FAILED - [].==("value") failed
```

Any other ways of trying to find the view have failed as well. I either get `nil` or an empty array as in the above error.

My question is, how can I check that my views have the correct data in my view spec?

### PR DESCRIPTION
**Pull request by squidpunch**
* Closes #74

### CODE REVIEW

**Comment by twerth** [comment]
rmq(self) should only apply to a UIView, not any object. We can override UIView and UIViewController to use the correct view to wrap.

**Comment by squidpunch** [comment]
I assumed that it would be fine on any object, though that makes sense, I can update this PR to work that way :+1: 

thanks for reviewing @twerth

**Comment by squidpunch** [comment]
@twerth I think we only need to attach to UIView, the controller generally seems to work correctly pushing an adjusted commit now

**Comment by twerth** [comment]
Thanks David. 

We should do controller too, rmq is smart enough to find the controller, but that process is slower than just wrapping `rmq(self.view)`.

**Comment by squidpunch** [comment]
oh! rmq(self.view) thats probably why i was seeing errors when I tried to add it, I will update again!

**Comment by squidpunch** [comment]
@twerth controller method included as well.

File: lib/project/ext/ui_view.rb [hunk 1]
```diff
@@ -82,7 +82,12 @@ def image
   def stylesheet
     rmq.stylesheet
   end
+
   def stylesheet=(value)
     rmq.stylesheet = value
   end
+
+  def find(*args)
+    rmq(self).find(args)
```
Comment (jamonholmgren) [inline lib/project/ext/ui_view.rb]: Shouldn't this have been:

```ruby
def find(*args)
  rmq(self).find(*args)
end
```

File: lib/project/ext/ui_view_controller.rb [hunk 2]
```diff
@@ -46,12 +46,19 @@ def image
   def stylesheet
     rmq.stylesheet
   end
+
   def stylesheet=(value)
     rmq.stylesheet = value
   end
+
+  def find(*args)
+    rmq(self.view).find(args)
```
Comment (jamonholmgren) [inline lib/project/ext/ui_view_controller.rb]: Same here?

File: lib/project/ext/ui_view.rb (hunk 1 above)
Comment (squidpunch) [inline lib/project/ext/ui_view.rb]: I mirrored this after what we had in object, but yeah, I think you're right - I'll throw together a test and verify and get another PR together.  Thanks @jamonholmgren

Comment (jamonholmgren) [inline lib/project/ext/ui_view.rb]: It probably works (because @twerth is a fantastic software engineer who [accounts for things like this](https://github.com/infinitered/rmq/blob/ca07631fe6845abf8da1aca6a0b555740928422c/motion/ruby_motion_query/selectors.rb#L60)), but the `*args` is more correct.

Comment (squidpunch) [inline lib/project/ext/ui_view.rb]: heh Yeah I figured there was a flatten in there, etc.  anyway I am plan to fix it today :+1:

**Comment by twerth** [comment]
This isn't right, making PR to discuss it.
